spring:
  mvc:
    hidden-method:
      filter:
        enabled: true # Rest 风格
    path-match:
      matching-strategy: ant_path_matcher # Swagger 路径匹配
  jackson:
    serialization:
      write-dates-as-timestamps: true   # 将 时间 转换为 时间戳
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 20MB   # 提高上传文件的大小
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.217.9:3306/tikfake?characterEncoding=utf-8
    username: infinite
    password: Zcj119303
  redis:
    host: 47.115.217.9
    port: 6379
    database: 0
    password: Zcj119303

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增

qiniu:
  accessKey: CQwDB_qxHOG4oRWM98WtnhINjsInqUDo4qrPdsLB
  secretKey: 3rqpIliuvCUNnBXoqIpLi1kQp8dlvXF09890_bfn
  bucket: tikfake
  domain: http://rqdsogyxa.hd-bkt.clouddn.com/